"""Add is_processed field

Revision ID: 848f1b10ba35
Revises: adaa3ad79afa
Create Date: 2025-04-12 19:50:44.259415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848f1b10ba35'
down_revision: Union[str, None] = 'adaa3ad79afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_record_transcriptions', sa.Column('is_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_record_transcriptions', 'is_processed')
    # ### end Alembic commands ###
