name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-server:
    name: Build MedVoice Server App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          cd backend
          poetry install

      - name: Build CLI with PyInstaller
        run: |
          cd backend
          poetry run pyinstaller cli.spec

      - name: Upload Server CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-cli
          path: backend/dist/  # Adjust if binary is in a subfolder

  build-tauri-windows:
    name: Build Tauri Windows Installer
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Install Tauri + Nuxt dependencies
        run: |
          cd gui
          yarn install 
      

      - name: Build Tauri Windows Installer
        run: |
          cd gui
          yarn tauri build

      - name: Upload Tauri Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui-msi
          path: |
            gui/src-tauri/target/release/bundle/msi/*.msi

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-server, build-tauri-windows]

    permissions:
      contents: write  
      id-token: write 

    steps:
      - uses: actions/checkout@v4

      - name: Download Server CLI
        uses: actions/download-artifact@v4
        with:
          name: backend-cli
          path: release/backend
          

      - name: Download Tauri MSI
        uses: actions/download-artifact@v4
        with:
          name: gui-msi
          path: release/gui

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/backend/**
            release/gui/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
